base_url = "https://tnychn.github.io"

title = "tnychn"
author = "Tony Chan (tnychn)"

default_language = "en-HK"

minify_html = false
compile_sass = false
generate_feeds = false
build_search_index = false
generate_sitemap = true
generate_robots_txt = true

[markdown]
highlight_code = true
error_on_missing_highlight = false
highlight_theme = "gruvbox-dark"
render_emoji = true
bottom_footnotes = true

[extra]
email = "tnychn@pm.me"
socials = { github = "https://github.com/tnychn" }
[[extra.navlinks]]
title = "About"
path = "/"
[[extra.navlinks]]
title = "Blog"
path = "/blog"
