name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      - name: Publish
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
